export const adminCopy = {
  dashboard: "Dashboard",
  labeling: "Labeling",
  review: "Review",
  quality: "Data quality",
  catalog: "Catalog",
  signOut: "Sign out",
  adminAccess: "Admin access",
  secret: "Shared secret",
  enter: "Enter",
  snapshotRuns: "Snapshot runs",
  matchRun: "Match run",
  statusByBag: "Status by bag",
  goldProgress: "Gold progress",
  noRows: "No rows",
  accept: "Accept",
  reject: "Reject",
  skip: "Skip",
  previous: "Previous",
  status: "Status",
  confidence: "Confidence",
  trace: "Trace",
  ruleHits: "Rule hits",
  exclusions: "Exclusions",
  reason: "Reason",
  variant: "Variant",
  color: "Color",
  condition: "Condition",
  completeness: "Completeness",
  strap: "Strap",
  lock: "Lock",
  key: "Key",
  dustBag: "Dust bag",
  cards: "Cards",
  query: "Query",
  seller: "Seller",
  noImage: "No image",
  approve: "Approve",
  reassign: "Reassign",
  item: "Item",
  price: "Price",
  action: "Action",
  keys: "Keys",
  close: "Close",
  bandCoverage: "Band coverage",
  possibleRelists: "Possible relists",
  listingsThatEnded: "Listings that ended",
  unbandedShare: "Unbanded share",
  variantCoverage: "Variant coverage",
  alarms: "Alarms",
  recomputeRequired: "Recompute required",
  aliases: "Aliases",
  variants: "Variants",
  globalExclusions: "Global exclusions",
  editorial: "Editorial",
  save: "Save",
  add: "Add",
  delete: "Delete",
  createBag: "Create bag",
  score: "Score audit",
  shadowMode: "Shadow mode — internal only, not published",
  timeline: "Score timeline",
  components: "Components",
  gateHistory: "Gate history",
  decomposition: "Day-over-day decomposition",
  searchSignal: "Search signal",
  bucket: "Bucket",
  eligible: "Eligible",
  weight: "Weight",
  contribution: "Contribution",
  rawScore: "Raw",
  smoothed: "Smoothed",
  publicationTrack: "Publication track",
  classification: "Classification",
  direction: "Direction",
  notScored: "Not yet scored",
} as const;

export const scoreComponentLabels: Record<string, string> = {
  search_momentum: "Search momentum",
  active_inventory_momentum: "Active inventory momentum",
  asking_price_momentum: "Asking-price momentum",
  marketplace_breadth: "Marketplace breadth",
  listing_turnover_proxy: "Listing turnover",
};

export const rejectionReasons = [
  "wrong_model",
  "wrong_product_category",
  "accessory_replacement_part",
  "replica_or_inspired",
  "seller_misuses_model_name",
  "child_mini_variant_mismatched",
  "bundle_or_lot",
  "wanted_to_buy",
  "indeterminate",
  "duplicate_relist",
] as const;

export const conditionBands = [
  "new_or_unused",
  "excellent",
  "very_good",
  "good",
  "fair",
  "poor",
] as const;
