export const adminCopy = {
  dashboard: "Dashboard",
  labeling: "Labeling",
  review: "Review",
  signOut: "Sign out",
  adminAccess: "Admin access",
  secret: "Shared secret",
  enter: "Enter",
  snapshotRuns: "Snapshot runs",
  matchRun: "Match run",
  statusByBag: "Status by bag",
  goldProgress: "Gold progress",
  noRows: "No rows",
  accept: "Accept",
  reject: "Reject",
  skip: "Skip",
  previous: "Previous",
  status: "Status",
  confidence: "Confidence",
  trace: "Trace",
  ruleHits: "Rule hits",
  exclusions: "Exclusions",
  reason: "Reason",
  variant: "Variant",
  color: "Color",
  condition: "Condition",
  completeness: "Completeness",
  strap: "Strap",
  lock: "Lock",
  key: "Key",
  dustBag: "Dust bag",
  cards: "Cards",
  query: "Query",
  seller: "Seller",
  noImage: "No image",
  approve: "Approve",
  reassign: "Reassign",
  item: "Item",
  price: "Price",
  action: "Action",
  keys: "Keys",
  close: "Close",
} as const;

export const rejectionReasons = [
  "wrong_model",
  "wrong_product_category",
  "accessory_replacement_part",
  "replica_or_inspired",
  "seller_misuses_model_name",
  "child_mini_variant_mismatched",
  "bundle_or_lot",
  "wanted_to_buy",
  "indeterminate",
  "duplicate_relist",
] as const;

export const conditionBands = [
  "new_or_unused",
  "excellent",
  "very_good",
  "good",
  "fair",
  "poor",
] as const;
