"""Additional catalog bags beyond the original 5-bag pilot.

Kept in a separate module so the primary ``seeds/catalog.py`` stays readable.
``seed()`` iterates the combined ``CATALOG`` list. Editorial history is optional
(left out here); summary + condition notes + expected range are concise but real.
Each bag also needs a profile in ``jobs/seed_history.py`` to render cross-day data.
"""

from __future__ import annotations

from app.contract import AliasType, RejectionReason, VariantKind

A = AliasType
V = VariantKind
R = RejectionReason


def _bag(
    *,
    brand_slug: str,
    brand_name: str,
    slug: str,
    model_name: str,
    era: str,
    summary: str,
    conditions: str,
    price_note: str,
    queries: list[str],
    aliases: list[tuple[str, AliasType]],
    variants: list[tuple[str, VariantKind, str, bool]],
    exclusions: list[tuple[str, RejectionReason]],
) -> dict:
    return {
        "brand": {"slug": brand_slug, "name": brand_name},
        "slug": slug,
        "model_name": model_name,
        "era": era,
        "expected_range_note": price_note,
        "editorial_summary": summary,
        "editorial_condition_notes": conditions,
        "initial_queries": queries,
        "aliases": aliases,
        "variants": variants,
        "exclusions": exclusions,
    }


EXTRA_CATALOG: list[dict] = [
    _bag(
        brand_slug="chanel", brand_name="Chanel", slug="chanel-25", model_name="25",
        era="Introduced 2024",
        summary="The Chanel 25 is a soft, slouchy 2020s flap built for everyday wear with a large CC turn-lock.",
        conditions="Chain wear, leather slouch collapse, and CC hardware plating are first-order signals.",
        price_note="Expected asking range: about $3,600 Good to $6,800 New or unused.",
        queries=["chanel 25 bag", "chanel 25 flap"],
        aliases=[("Chanel 25 Handbag", A.alias), ("chanel 25 medium", A.marketplace_term)],
        variants=[("Small", V.size, "Canonical smaller size.", False), ("Medium", V.size, "Larger everyday size.", False)],
        exclusions=[("Chanel 19", R.wrong_model), ("Chanel 22", R.wrong_model), ("classic flap", R.wrong_model)],
    ),
    _bag(
        brand_slug="dior", brand_name="Dior", slug="dior-gaucho", model_name="Gaucho",
        era="John Galliano for Dior, 2006",
        summary="The Gaucho Saddle is Galliano-era Dior's oversized double-buckle saddle in distressed leather.",
        conditions="Distressed-finish rubbing, oversized buckle tarnish, and strap wear dominate condition reads.",
        price_note="Expected asking range: about $340 Fair to $1,100 Excellent.",
        queries=["dior gaucho bag", "dior gaucho saddle"],
        aliases=[("Dior Gaucho Saddle Bag", A.alias), ("galliano gaucho", A.marketplace_term)],
        variants=[("Large", V.size, "Oversized single saddle.", False), ("Double Saddle", V.edition, "Double-pouch variant.", False)],
        exclusions=[("Dior Saddle", R.wrong_model), ("gaucho belt", R.wrong_product_category)],
    ),
    _bag(
        brand_slug="dior", brand_name="Dior", slug="dior-columbus", model_name="Columbus",
        era="Christian Dior, early 2000s",
        summary="The Columbus is an early-2000s Dior shoulder bag from the Galliano logo era.",
        conditions="Coated-canvas cracking, piping wear, and hardware tarnish are primary.",
        price_note="Expected asking range: about $240 Fair to $520 Very good.",
        queries=["dior columbus bag", "dior columbus avenue"],
        aliases=[("Dior Columbus Avenue", A.alias)],
        variants=[("Shoulder", V.size, "Standard shoulder shape.", False)],
        exclusions=[("Dior Saddle", R.wrong_model), ("columbus map", R.wrong_product_category)],
    ),
    _bag(
        brand_slug="saint-laurent", brand_name="Saint Laurent", slug="ysl-mombasa", model_name="Mombasa",
        era="Tom Ford for YSL, 2002",
        summary="The Mombasa is Tom Ford-era YSL's crescent hobo with a signature curved horn handle.",
        conditions="Horn-handle cracking, leather slouch, and lining wear are first-order.",
        price_note="Expected asking range: about $820 Good to $1,900 New or unused.",
        queries=["ysl mombasa bag", "yves saint laurent mombasa"],
        aliases=[("Saint Laurent Mombasa", A.alias), ("tom ford mombasa", A.marketplace_term)],
        variants=[("Horn handle", V.edition, "Signature horn-handle version.", False)],
        exclusions=[("mombasa kenya", R.wrong_product_category), ("YSL Muse", R.wrong_model)],
    ),
    _bag(
        brand_slug="miu-miu", brand_name="Miu Miu", slug="miu-miu-vitello", model_name="Vitello",
        era="Miu Miu leather line, 2010s",
        summary="Miu Miu's Vitello leather bags are supple calf-leather styles known for matelasse and bow detailing.",
        conditions="Leather softening, corner rubs, and hardware plating are primary.",
        price_note="Expected asking range: about $260 Fair to $620 Excellent.",
        queries=["miu miu vitello bag", "miu miu vitello lux"],
        aliases=[("Miu Miu Vitello Lux", A.alias), ("miu miu vitello shine", A.marketplace_term)],
        variants=[("Bow", V.edition, "Bow-detail styles.", False), ("Matelasse", V.edition, "Quilted matelasse styles.", False)],
        exclusions=[("Prada Vitello", R.wrong_model)],
    ),
    _bag(
        brand_slug="chloe", brand_name="Chloé", slug="chloe-silverado", model_name="Silverado",
        era="Phoebe Philo for Chloé, 2004-2005",
        summary="The Silverado is a mid-2000s Chloé hobo with wooden ring handles and slouchy leather.",
        conditions="Wooden-ring cracking, leather slouch, and strap wear are primary.",
        price_note="Expected asking range: about $320 Fair to $780 Excellent.",
        queries=["chloe silverado bag", "chloe silverado hobo"],
        aliases=[("Chloe Silverado Hobo", A.alias)],
        variants=[("Large", V.size, "Full-size hobo.", False), ("Medium", V.size, "Smaller version.", False)],
        exclusions=[("Chloe Paddington", R.wrong_model), ("Chloe Edith", R.wrong_model)],
    ),
    _bag(
        brand_slug="gucci", brand_name="Gucci", slug="gucci-indy", model_name="Indy",
        era="Frida Giannini for Gucci, 2008",
        summary="The Indy is a late-2000s Gucci top-handle hobo with fringe tassel and buckle detail.",
        conditions="Fringe-tassel wear, GG-canvas rubbing, and buckle tarnish are primary.",
        price_note="Expected asking range: about $300 Good to $720 Excellent.",
        queries=["gucci indy bag", "gucci indy hobo"],
        aliases=[("Gucci Indy Top Handle", A.alias)],
        variants=[("Large", V.size, "Full-size top handle.", False)],
        exclusions=[("Gucci Jackie", R.wrong_model)],
    ),
    _bag(
        brand_slug="prada", brand_name="Prada", slug="prada-bonnie", model_name="Bonnie",
        era="Prada, 2010s",
        summary="The Bonnie is a Prada leather bowling-adjacent bag from the 2010s.",
        conditions="Saffiano corner wear and hardware plating are primary.",
        price_note="Expected asking range: about $300 Fair to $520 Very good.",
        queries=["prada bonnie bag", "prada bonnie bauletto"],
        aliases=[("Prada Bonnie Bauletto", A.alias)],
        variants=[("Medium", V.size, "Standard size.", False)],
        exclusions=[("Prada Bowling", R.wrong_model)],
    ),
    _bag(
        brand_slug="louis-vuitton", brand_name="Louis Vuitton", slug="louis-vuitton-pochette", model_name="Pochette",
        era="Louis Vuitton, 1990s-2000s",
        summary="The Pochette is Louis Vuitton's compact zip-top shoulder pouch, a Y2K staple in Monogram.",
        conditions="Vachetta patina, zipper wear, and strap cracking are primary.",
        price_note="Expected asking range: about $190 Poor to $520 Excellent.",
        queries=["louis vuitton pochette", "lv pochette bag"],
        aliases=[("LV Pochette", A.alias), ("louis vuitton pochette monogram", A.marketplace_term)],
        variants=[("Monogram", V.color_family, "Classic Monogram.", False), ("Multicolore", V.color_family, "Murakami Multicolore.", False)],
        exclusions=[("Pochette Accessoires", R.wrong_model), ("Pochette Metis", R.wrong_model), ("wallet", R.wrong_product_category)],
    ),
    _bag(
        brand_slug="fendi", brand_name="Fendi", slug="fendi-spy", model_name="Spy",
        era="Fendi, 2005",
        summary="The Spy is a mid-2000s Fendi hobo with a hidden coin compartment and rope handle, here in leather.",
        conditions="Leather slouch, rope-handle wear, and secret-compartment hardware are primary.",
        price_note="Expected asking range: about $460 Fair to $1,600 New or unused.",
        queries=["fendi spy bag", "fendi spy leather"],
        aliases=[("Fendi Spy Hobo", A.alias)],
        variants=[("Leather", V.color_family, "Solid-leather versions.", False)],
        exclusions=[("Fendi Baguette", R.wrong_model), ("spy zucca", R.wrong_model)],
    ),
    _bag(
        brand_slug="gucci", brand_name="Gucci", slug="gucci-jackie", model_name="Jackie",
        era="Gucci heritage 1960s / 2000s reissue",
        summary="The Jackie is Gucci's piston-lock hobo, named for Jackie Kennedy and reissued across decades.",
        conditions="Piston-lock spring function, GG-canvas rubbing, and strap wear are primary.",
        price_note="Expected asking range: about $640 Good to $1,500 New or unused.",
        queries=["gucci jackie bag", "gucci jackie piston lock"],
        aliases=[("Gucci Jackie Hobo", A.alias), ("gucci new jackie", A.marketplace_term)],
        variants=[("Piston lock", V.edition, "Classic piston-lock closure.", False)],
        exclusions=[("Gucci Indy", R.wrong_model)],
    ),
    _bag(
        brand_slug="chanel", brand_name="Chanel", slug="chanel-suede-flap", model_name="Suede Flap",
        era="Vintage Chanel, 1980s-1990s",
        summary="Vintage Chanel suede flap bags pair CC turn-locks with delicate napped suede, prized and fragile.",
        conditions="Suede staining, nap flattening, and chain plating are first-order and hard to restore.",
        price_note="Expected asking range: about $1,300 Fair to $3,200 Excellent.",
        queries=["chanel suede flap bag", "vintage chanel suede bag"],
        aliases=[("Chanel Suede Classic Flap", A.alias)],
        variants=[("Small", V.size, "Small flap.", False), ("Medium", V.size, "Medium flap.", False)],
        exclusions=[("caviar", R.wrong_model), ("lambskin", R.wrong_model), ("Chanel 19", R.wrong_model)],
    ),
    _bag(
        brand_slug="miu-miu", brand_name="Miu Miu", slug="miu-miu-nappa", model_name="Nappa",
        era="Miu Miu, 2000s-2010s",
        summary="Miu Miu's Nappa leather bags are soft gathered-leather styles, including the Coffer and bow shapes.",
        conditions="Gathered-leather slouch, corner rubs, and hardware plating are primary.",
        price_note="Expected asking range: about $230 Fair to $560 Excellent.",
        queries=["miu miu nappa bag", "miu miu coffer"],
        aliases=[("Miu Miu Nappa Leather Bag", A.alias), ("miu miu coffer", A.marketplace_term)],
        variants=[("Coffer", V.edition, "Gathered Coffer shape.", False), ("Bow", V.edition, "Bow-detail styles.", False)],
        exclusions=[("Miu Miu Vitello", R.wrong_model)],
    ),
    _bag(
        brand_slug="miu-miu", brand_name="Miu Miu", slug="miu-miu-pocket", model_name="Pocket",
        era="Miu Miu, 2022-",
        summary="The Miu Miu Pocket is a 2020s soft nappa hobo with a curved single strap and minimal hardware.",
        conditions="Nappa slouch, strap wear, and edge-paint rubbing are primary.",
        price_note="Expected asking range: about $680 Good to $1,500 New or unused.",
        queries=["miu miu pocket bag", "miu miu pocket nappa"],
        aliases=[("Miu Miu Pocket Hobo", A.alias)],
        variants=[("Small", V.size, "Small pocket bag.", False), ("Medium", V.size, "Medium pocket bag.", False)],
        exclusions=[("Miu Miu Wander", R.wrong_model), ("Miu Miu Arcadie", R.wrong_model)],
    ),
    _bag(
        brand_slug="balenciaga", brand_name="Balenciaga", slug="balenciaga-rodeo", model_name="Rodeo",
        era="Balenciaga, 2024-",
        summary="The Rodeo is a 2020s Balenciaga slouchy hobo with a signature knotted strap and studded flap.",
        conditions="Strap-knot wear, studded-hardware plating, and leather slouch are primary.",
        price_note="Expected asking range: about $1,400 Good to $2,600 New or unused.",
        queries=["balenciaga rodeo bag", "balenciaga le rodeo"],
        aliases=[("Balenciaga Rodeo Hobo", A.alias), ("balenciaga le rodeo", A.marketplace_term)],
        variants=[("Small", V.size, "Small Rodeo.", False), ("Medium", V.size, "Medium Rodeo.", False)],
        exclusions=[("Balenciaga City", R.wrong_model), ("Balenciaga Cagole", R.wrong_model)],
    ),
    _bag(
        brand_slug="prada", brand_name="Prada", slug="prada-bowling", model_name="Bowling",
        era="Prada, early 2000s",
        summary="The Prada Bowling (Bauletto) is a structured early-2000s doctor-bag silhouette in nylon or leather.",
        conditions="Nylon fraying, base-corner wear, and zipper function are primary.",
        price_note="Expected asking range: about $180 Poor to $480 Very good.",
        queries=["prada bowling bag", "prada bauletto"],
        aliases=[("Prada Bauletto", A.alias), ("prada bowling nylon", A.marketplace_term)],
        variants=[("Nylon", V.color_family, "Tessuto nylon versions.", False), ("Leather", V.color_family, "Leather versions.", False)],
        exclusions=[("Prada Bonnie", R.wrong_model)],
    ),
]
